# Week 2 Pre-Class Assignment 3

## Problem 1

In [1]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

We will explain the calculation process of the matrix poduct (using the above matrix)
- Let's say that the result of the product of matrix A and matrix B is matrix C.
- Let's also say that matrix is as follow: c_ndarray = np.array([[c11, c12, c13], [c21, c22, c23], [c31, c32, c33]])
- Now, let's calculate the values manually.
    - c11 = (-1)(0) + 2(0) + 3(2) = **6** 
    - c12 = (-1)(2) + 2(2) + 3(9) = **29**
    - c13 = (-1)(1) + 2(-8) + 3(-1) = **-20**
    - c21 = 4(0) + (-5)(0) + 6(2) = **12**
    - c22 = 4(2) + (-5)(2) + 6(9) = **52**
    - c23 = 4(1) + (-5)(-8) + 6(-1) = **38**
    - c31 = 7(0) + 8(0) + (-9)2 = **-18**
    - c32 = 7(2) + 8(2) + (-9)(9) = **-51**
    - c33 = 7(1) + 8(-8) + (-9)(-1) = **-48**

## Problem 2

In [2]:
np.dot(a_ndarray,b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

## Problem 3

In [6]:
C = np.zeros((3,3))
valueof_0th_raw_and_column = 0
for i in range(C.shape[0]):
    valueof_0th_raw_and_column += a_ndarray[0,i] * b_ndarray[i,0]
print('The value of Oth raw and 0th column after the product of Matrix A and B is: {}'.format(valueof_0th_raw_and_column))

The value of Oth raw and 0th column after the product of Matrix A and B is: 6


## Problem 4

In [8]:
def matrix_multiplication(a,b):
    C = np.zeros((a.shape[0],b.shape[1]))
    for i in range(C.shape[0]):
        for j in range(C.shape[1]):
            for k in range(a.shape[1]):
                 C[i,j] += a[i,k]*b[k,j]
    return C

In [9]:
matrix_multiplication(a_ndarray[1:,:],b_ndarray)

array([[ 12.,  52.,  38.],
       [-18., -51., -48.]])

- As we can see in the last result, it is possible to perform the multiplication even when the number of columns of A isn't equal to the number of rows of B. We will sove this issue on the next problem

## Problem 5

In [12]:
def better_matrix_multiplication(a,b):
    C = np.zeros((a.shape[0],b.shape[1]))
    if a.shape[1] == b.shape[0]:
        for i in range(C.shape[0]):
            for j in range(C.shape[1]):
                for k in range(a.shape[1]):
                    C[i,j] += a[i,k]*b[k,j]
        return C
    else:
        print('The number of columns of the first matrix is different from the number of colums of the other one. You are trying a product of {} and {}.'.format(a.shape,b.shape)) 
        return None

- Now let's check the function with the given examples in the curriculum (D and E)

In [13]:
d_ndarray_ = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
better_matrix_multiplication(d_ndarray_,e_ndarray)

The number of columns of the first matrix is different from the number of colums of the other one. You are trying a product of (2, 3) and (2, 3).


## Problem 6

In [15]:
print(np.dot(d_ndarray_.T,e_ndarray))

[[ 33 -28   9]
 [-48  41  -6]
 [  9  -6  45]]
