# Week 4 Lesson Assignment

## Problem 1

- We learn here the customer's information and predict TARGET
- We enter the predicted probability for the TARGET variable in sample_submission.csv
- AUC is the kind of index value the submitted items will be evaluated

## Problem 2

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

df = pd.read_csv('application_train.csv')

In [2]:
df.head()

SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
0      100002       1         Cash loans           M            N   
1      100003       0         Cash loans           F            N   
2      100004       0    Revolving loans           M            Y   
3      100006       0         Cash loans           F            N   
4      100007       0         Cash loans           M            N   

  FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  \
0               Y             0          202500.0    406597.5      24700.5   
1               N             0          270000.0   1293502.5      35698.5   
2               Y             0           67500.0    135000.0       6750.0   
3               Y             0          135000.0    312682.5      29686.5   
4               Y             0          121500.0    513000.0      21865.5   

   ...  FLAG_DOCUMENT_18 FLAG_DOCUMENT_19 FLAG_DOCUMENT_20 FLAG_DOCUMENT_21  \
0  ...                 0                0                0                0   
1  ...                 0                0                0                0   
2  ...                 0                0                0                0   
3  ...                 0                0                0                0   
4  ...                 0                0                0                0   

  AMT_REQ_CREDIT_BUREAU_HOUR AMT_REQ_CREDIT_BUREAU_DAY  \
0                        0.0                       0.0   
1                        0.0                       0.0   
2                        0.0                       0.0   
3                        NaN                       NaN   
4                        0.0                       0.0   

   AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
0                         0.0                        0.0   
1                         0.0                        0.0   
2                         0.0                        0.0   
3                         NaN                        NaN   
4                         0.0                        0.0   

   AMT_REQ_CREDIT_BUREAU_QRT  AMT_REQ_CREDIT_BUREAU_YEAR  
0                        0.0                         1.0  
1                        0.0                         0.0  
2                        0.0                         0.0  
3                        NaN                         NaN  
4                        0.0                         0.0  

[5 rows x 122 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Columns: 122 entries, SK_ID_CURR to AMT_REQ_CREDIT_BUREAU_YEAR
dtypes: float64(65), int64(41), object(16)
memory usage: 286.2+ MB


In [4]:
df_2 = pd.get_dummies(df)
from sklearn.impute import SimpleImputer
df_3 = df_2.loc[:,['EXT_SOURCE_1','EXT_SOURCE_2', 'EXT_SOURCE_3']] 
imr = SimpleImputer()
df_imp = imr.fit_transform(df_3)
df_imp

array([[0.08303697, 0.26294859, 0.13937578],
       [0.31126731, 0.62224578, 0.51085291],
       [0.50212981, 0.55591208, 0.72956669],
       ...,
       [0.7440264 , 0.53572175, 0.21885908],
       [0.50212981, 0.51416282, 0.66102354],
       [0.73445967, 0.7085689 , 0.1139224 ]])

In [7]:
y = df.loc[:,'TARGET']

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score

X_train,X_test,y_train,y_test = train_test_split(df_imp,y,test_size=0.2,stratify=y)

lr = LogisticRegression()
lr = lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)

score = roc_auc_score(y_test, y_pred)

/Users/diopmouhamed/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [8]:
print(y_pred.shape)
print('test_roc_auc_score: ', score)

(61503,)
test_roc_auc_score:  0.5021427665311644


## Problem 3

In [12]:
test = pd.read_csv('application_test.csv')
test.head()

SK_ID_CURR NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR FLAG_OWN_REALTY  \
0      100001         Cash loans           F            N               Y   
1      100005         Cash loans           M            N               Y   
2      100013         Cash loans           M            Y               Y   
3      100028         Cash loans           F            N               Y   
4      100038         Cash loans           M            Y               N   

   CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  AMT_GOODS_PRICE  \
0             0          135000.0    568800.0      20560.5         450000.0   
1             0           99000.0    222768.0      17370.0         180000.0   
2             0          202500.0    663264.0      69777.0         630000.0   
3             2          315000.0   1575000.0      49018.5        1575000.0   
4             1          180000.0    625500.0      32067.0         625500.0   

   ... FLAG_DOCUMENT_18 FLAG_DOCUMENT_19 FLAG_DOCUMENT_20 FLAG_DOCUMENT_21  \
0  ...                0                0                0                0   
1  ...                0                0                0                0   
2  ...                0                0                0                0   
3  ...                0                0                0                0   
4  ...                0                0                0                0   

  AMT_REQ_CREDIT_BUREAU_HOUR  AMT_REQ_CREDIT_BUREAU_DAY  \
0                        0.0                        0.0   
1                        0.0                        0.0   
2                        0.0                        0.0   
3                        0.0                        0.0   
4                        NaN                        NaN   

   AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
0                         0.0                        0.0   
1                         0.0                        0.0   
2                         0.0                        0.0   
3                         0.0                        0.0   
4                         NaN                        NaN   

   AMT_REQ_CREDIT_BUREAU_QRT  AMT_REQ_CREDIT_BUREAU_YEAR  
0                        0.0                         0.0  
1                        0.0                         3.0  
2                        1.0                         4.0  
3                        0.0                         3.0  
4                        NaN                         NaN  

[5 rows x 121 columns]

In [13]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48744 entries, 0 to 48743
Columns: 121 entries, SK_ID_CURR to AMT_REQ_CREDIT_BUREAU_YEAR
dtypes: float64(65), int64(40), object(16)
memory usage: 45.0+ MB


In [15]:
test_2 = test.loc[:,['EXT_SOURCE_1','EXT_SOURCE_2', 'EXT_SOURCE_3']]
test_2.head()

EXT_SOURCE_1  EXT_SOURCE_2  EXT_SOURCE_3
0      0.752614      0.789654      0.159520
1      0.564990      0.291656      0.432962
2           NaN      0.699787      0.610991
3      0.525734      0.509677      0.612704
4      0.202145      0.425687           NaN

In [17]:
test_imp = SimpleImputer()
test_imp_2 = test_imp.fit_transform(test_2)
y_test_pred = lr.predict(np.array(test_imp_2))

In [18]:
submission = pd.read_csv('./sample_submission.csv')
submission['TARGET'] = y_test_pred
submission['SK_ID_CURR'] = test.loc[:,'SK_ID_CURR']
submission.to_csv('./submission.csv', index=False)

- We did the submission successfully and the score is 0.50266, we will try to improve it in the following part.

## Problem 4

In [27]:
new_test = df.copy()
del new_test['TARGET']
X = new_test
y = df["TARGET"]

In [43]:
mask = np.array(X.dtypes != '0' )
idx = np.arange(len(X.columns))
X = X.iloc[:,mask]

1. Let's first use the average value

In [44]:
X = np.array(X)
y = np.array(y)
(X_train, X_test, y_train, y_test) = train_test_split(X, y, test_size=0.25, random_state=0,)

import lightgbm as lgb
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

smp = SimpleImputer()
X_train_smp = smp.fit_transform(X_train)
X_test_smp = smp.fit_transform(X_test)
clf = lgb.LGBMClassifier().fit(X_train_smp, y_train)
y_pred = clf.predict(X_test_smp)
print(clf)
print("{}".format(clf.score(X_test, y_test)))
print("{}".format(precision_score(y_test,y_pred)))
print("{}".format(recall_score(y_test,y_pred)))
print("{}".format(f1_score(y_test,y_pred)))
print(confusion_matrix(y_test,y_pred))

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=True,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)
0.8220036941647806
0.5478260869565217
0.010343129207026762
0.020302932645826624
[[70735    52]
 [ 6028    63]]


2. Next, let's use the median

In [45]:
smp = SimpleImputer(strategy='median')
X_train_smp = smp.fit_transform(X_train)
X_test_smp = smp.fit_transform(X_test)
clf = lgb.LGBMClassifier().fit(X_train_smp, y_train)
y_pred = clf.predict(X_test_smp)
print(clf)
print("{}".format(clf.score(X_test, y_test)))
print("{}".format(precision_score(y_test,y_pred)))
print("{}".format(recall_score(y_test,y_pred)))
print("{}".format(f1_score(y_test,y_pred)))
print(confusion_matrix(y_test,y_pred))

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=True,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)
0.8688181274226697
0.5666666666666667
0.016746018716138567
0.03253069685855526
[[70709    78]
 [ 5989   102]]


3. Let's now use the mode

In [46]:
smp = SimpleImputer(strategy='most_frequent')
X_train_smp = smp.fit_transform(X_train)
X_test_smp = smp.fit_transform(X_test)
clf = lgb.LGBMClassifier().fit(X_train_smp, y_train)
y_pred = clf.predict(X_test_smp)
print(clf)
print("{}".format(clf.score(X_test, y_test)))
print("{}".format(precision_score(y_test,y_pred)))
print("{}".format(recall_score(y_test,y_pred)))
print("{}".format(f1_score(y_test,y_pred)))
print(confusion_matrix(y_test,y_pred))

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=True,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)
0.8825281615026406
0.50920245398773
0.013626662288622558
0.02654301247201791
[[70707    80]
 [ 6008    83]]


4. Now, let's use the constant

In [47]:
smp = SimpleImputer(strategy='constant')
X_train_smp = smp.fit_transform(X_train)
X_test_smp = smp.fit_transform(X_test)
clf = lgb.LGBMClassifier().fit(X_train_smp, y_train)
y_pred = clf.predict(X_test_smp)
print(clf)
print("{}".format(clf.score(X_test, y_test)))
print("{}".format(precision_score(y_test,y_pred)))
print("{}".format(recall_score(y_test,y_pred)))
print("{}".format(f1_score(y_test,y_pred)))
print(confusion_matrix(y_test,y_pred))

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=True,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)
0.9208616249121986
0.519774011299435
0.015104252175340666
0.029355456285896617
[[70702    85]
 [ 5999    92]]


5. Now the last one

In [72]:
dfv = pd.read_csv('application_train.csv')
train_list = list(dfv.columns)
test_list = list(test.columns)
i_list = set(train_list) & set(test_list)

df_v2 = dfv
list_str=[]
for i in df_v2.columns:
    if df_v2[i].dtypes == 'O':
        df_v2 = df_v2.drop([i], axis = 1)
        list_str.append(i)
        
df_v2 = df_v2.replace(np.nan,0)
dfv_str = dfv[list_str]
dfv_dummy = pd.get_dummies(dfv_str)
dfv_mix = pd.concat([df_v2, dfv_dummy], axis=1)

df_v3 = test
for i in df_v3.columns:
    if df_v3[i].dtypes == 'O':
        df_v3 = df_v3.drop([i], axis = 1)
        list_str.append(i)
        
dfv_str2 = test[list_str]
dfv_dummy2 = pd.get_dummies(dfv_str2)
df_v3 = df_v3.replace(np.nan,0)
dfv_mix2 = pd.concat([df_v3, dfv_dummy2], axis=1)
i_list = set(list(dfv_mix.columns)) & set(list(dfv_mix2.columns))

dfv_mix = dfv_mix[i_list]
dfv_mix2 = dfv_mix2[i_list]
print(dfv_mix.shape)
print(dfv_mix2.shape)


(307511, 242)
(48744, 379)


In [74]:
from scipy.stats import pearsonr
list_i = []
for i in dfv_mix.columns: 
    a, b = pearsonr(dfv_mix[i],dfv["TARGET"])
    if 0.05 < abs(a) :
        list_i.append(i)
        print("{},{}".format(i,a))

REGION_RATING_CLIENT,0.05889901494571567
DAYS_BIRTH,0.07823930830982692
REG_CITY_NOT_WORK_CITY,0.05099446436813019
EXT_SOURCE_2,-0.15902967651017424
DAYS_ID_PUBLISH,0.05145717260705745
NAME_EDUCATION_TYPE_Higher education,-0.05659264414096195
NAME_INCOME_TYPE_Working,0.05748118481836794
REGION_RATING_CLIENT_W_CITY,0.06089266756482268
DAYS_LAST_PHONE_CHANGE,0.05521723161673506
EXT_SOURCE_1,-0.06469813333590202
CODE_GENDER_M,0.05471268197127452
CODE_GENDER_F,-0.054704053178807964
EXT_SOURCE_3,-0.11957192848712672


In [76]:
from sklearn.preprocessing import PolynomialFeatures
X = dfv_mix[list_i]
y = dfv["TARGET"]
X = np.array(X)
y = np.array(y)
poly = PolynomialFeatures(degree=3, include_bias=False)
poly.fit(X)
X_poly = poly.transform(X)

In [78]:
(X_train, X_test,y_train, y_test) = train_test_split(X_poly, y, test_size=0.25, random_state=0,)
clf = lgb.LGBMClassifier().fit(X_train, y_train)
y_pred = clf.predict(X_test)
y_pred =clf.predict(X_test)
print(clf)
print("{}".format(clf.score(X_test, y_test)))
print("{}".format(precision_score(y_test,y_pred)))
print("{}".format(recall_score(y_test,y_pred)))
print("{}".format(f1_score(y_test,y_pred)))
print(confusion_matrix(y_test,y_pred))

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=True,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)
0.9204713962381956
0.3944954128440367
0.007059596125430964
0.013870967741935485
[[70721    66]
 [ 6048    43]]


In [133]:
submission2 = pd.read_csv('./sample_submission.csv')
clf = lgb.LGBMClassifier().fit(X, y)

In [136]:
y_pred = clf.predict(np.array(test_2))

In [137]:
y_pred_proba =clf.predict_proba(test_2)

In [138]:
submission2["TARGET"] = y_pred_proba[:,1]
submission2.to_csv('./submission2.csv', index=False)

**The first score from Problem 3 (submission)**

<img src="1.png">

**The second score from Problem 4 (submission2)**

<img src="2.png">

**The score went up to 0.71358**