# Week 4 Pre-Class Assignment 3

## Problem 1

Let's enumerate one or more classes from Pandas, matplotlib and scikit-learn we have been using in the previous tasks

- Pandas: DataFrame, Series
- Matplotlib: figure,pyplot
- scikit-learn: LogisticRegression, Imputer

## Problem 2

Let's explain what kind of method and instance variable we have been using in the previous tasks

- Method
    - unique,array, zeros, ones, fit, predict, score ,len(), concatnate(), vstack(), hstack(), reshape()

- Instance variables
    - shape, index, columns, values, keys, dtypes, values, loc, iloc, coef_, ndim, shape, size, mean, var 

## Problem 3

In [1]:
class ScratchStandardScaler():

    def fit(self, X):
        n = X.shape[0]
        self.mean_ =np.sum(X,axis=0)/n
        self.var_ =np.sum(np.sqrt((X-self.mean_)**2),axis=0)/n
        pass

    def transform(self, X):  
        X_scaled = (X - self.mean_)/self.var_
        pass
    
        return X_scaled

In [2]:
import numpy as np
from sklearn.datasets import load_iris

data = load_iris()
X = data.data[:10]

scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("Average: {}".format(scratch_scaler.mean_))
print("Variance: {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

Average: [4.86 3.31 1.45 0.22]
Variance: [0.228 0.25  0.08  0.052]
[[ 1.05263158  0.76       -0.625      -0.38461538]
 [ 0.1754386  -1.24       -0.625      -0.38461538]
 [-0.70175439 -0.44       -1.875      -0.38461538]
 [-1.14035088 -0.84        0.625      -0.38461538]
 [ 0.61403509  1.16       -0.625      -0.38461538]
 [ 2.36842105  2.36        3.125       3.46153846]
 [-1.14035088  0.36       -0.625       1.53846154]
 [ 0.61403509  0.36        0.625      -0.38461538]
 [-2.01754386 -1.64       -0.625      -0.38461538]
 [ 0.1754386  -0.84        0.625      -2.30769231]]


## Problem 4

In [5]:
class ExampleClass():

    def __init__(self, value):
        self.value = value
        print("Initial value {} has been set".format(self.value))
        
    def add(self, value2):
        self.check_value(value2)
        self.value += value2
    
    def substraction(self,value3):
        self.check_value(value3)
        self.value -= value3
    
    def multiplication(self,value4):
        self.check_value(value4)
        self.value *= value4
    
    def division(self,value5):
        self.check_value(value5)
        self.value /= value5
        
    def check_value(self,value6):
        strsample = 'ddd'
        listsample = [1,2,3]
        arraysample = np.array([1,2,3])
        
        if type(value6) == type(strsample) or type(value6) == type(listsample) \
        or type(value6)  == type(arraysample):
            raise ValueError("The value you entered is not correct")
            
    

example = ExampleClass(5)
print("value: {}".format(example.value))
example.add(3)
print("value: {}".format(example.value))
example.substraction(2)
print("value: {}".format(example.value))
example.multiplication(3)
print("value: {}".format(example.value))
example.division(4)
print("value: {}".format(example.value))
example.substraction("diopmouhamed")

Initial value 5 has been set
value: 5
value: 8
value: 6
value: 18
value: 4.5


ValueError: The value you entered is not correct